title: Samira Kumar
description: Personal Blog about Sports, Analytics, Machine Learning and Data Visualisations.
# this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Samira Kumar # add your name
author-img: samira-kumar.jpg # add your photo
about-author: Data Scientist, blogging about sports analytics, machine learning and data visualisations
social-twitter: SamiraK93 # add your Twitter handle
social-github: samirak93 # add your Github handle
social-linkedin: samirakumar # add your Linkedin handle
social-email: samirakumar@yahoo.com # add your Email address
social-resume: https://github.com/samirak93/blog/blob/master/assets/img/Samira%20Kumar%20Varadharajan.pdf
# Disqus
discus-identifier: samirak93

# Tracker
analytics: UA-112742997-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 6
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
